#Server port
server:
  port: 8085
#Database props
spring:
  datasource:
    url: jdbc:h2:mem:haud
    driverClassName: org.h2.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2